name: Build (macOS)

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - electron-v3
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        default: ""
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: false
        required: false
        type: boolean

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [	macos-latest, ubuntu-latest, windows-latest ]
        os: [ macos-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Clone VencordDBC
        run: git clone https://github.com/aiko-chan-ai/VencordDBC.git

      - name: Install Dependencies
        run: npm run requirement

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: List all files (dist)
        run: ls dist

      - name: Create Draft Release
        if: ${{ inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          name: v${{ inputs.version }}
          files: dist/DiscordBotClient*
          draft: true
